language: php

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 1

services:

php:
  - 7.1
  - 7.2
  - master
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: master
    - php: nightly
  include:
    - php: 7.1
      env:
        - USE_XDEBUG=false
    - php: 7.2
      env:
        - USE_XDEBUG=false
    - php: 7.1
      env:
        - COVERAGE=true

install:
  - composer install

before_script:
  - if [[ ${USE_XDEBUG} == false ]]; then phpenv config-rm xdebug.ini; fi
  - php --version
  - php ./vendor/bin/phpunit --version

script:
  - php ./vendor/bin/phpunit

after_success:
  - if [[ $COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi

after_failure:
